config/routes.rb
SktBilling::Application.routes.draw do


  resources :companies


  resources :clients


  resources :bill_codes


  resources :bills


  resources :payments


  resources :directions


  resources :currencies


  resources :addresses


  resources :accounts


  resources :bill_items


  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :companies, :only => [:index, :update]
  resources :clients, :only => [:index, :update]
  resources :bills, :only => [:index, :show]
  resources :accounts, :only => [:index]
  resources :payments, :only => [:index]
  resources :directions, :only => [:index]
  resources :currencies, :only => [:index]
  resources :addresses, :only => [:index]


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  authenticated :user do
    root :to => 'bills#index'
  end
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    #get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#edit"    
    #match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/user.rb
class User < ActiveRecord::Base            
	# ----------------------------------------------------------------------
	rolify
	# ----------------------------------------------------------------------
	devise :database_authenticatable, :registerable, :confirmable, :recoverable, :rememberable, :trackable, :validatable
	# ----------------------------------------------------------------------	
	attr_accessible :role_ids, :as => :admin                                
	attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :created_at, :updated_at
	# ----------------------------------------------------------------------	
	def role?(role_sym)                                                     
	  roles.any? { |r| r.name.underscore.to_sym == role_sym }               
	end                                                                     
	# ----------------------------------------------------------------------
	# no password is required when the account is created; validate password when the user sets one
	# ----------------------------------------------------------------------
	validates_confirmation_of :password                                     
	def password_required?                                                  
	  if !persisted?                                                        
	    !(password != "")                                                   
	  else                                                                  
	    !password.nil? || !password_confirmation.nil?                       
	  end                                                                   
	end                                                                     
	# ----------------------------------------------------------------------
	# Send reset password instructions                                      
	# ----------------------------------------------------------------------
	def send_reset_password_instructions                                    
	  if self.confirmed?                                                    
	    super                                                               
	  else                                                                  
	    errors.add :base, "You must receive an invitation before you set your password."
	  end
	end  
	# ----------------------------------------------------------------------
	# override Devise method: no password confirmation required             
	# ----------------------------------------------------------------------
	def confirmation_required?                                              
	  false                                                                 
	end                                                                     
	# ----------------------------------------------------------------------
	# override Devise method: can auth only if confirmed or confirmation period has not expired
	# ----------------------------------------------------------------------
	def active_for_authentication?                                          
	  confirmed? || confirmation_period_valid?                              
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to set the password                                      
	# ----------------------------------------------------------------------
	def attempt_set_password(params)                                        
	  p = {}                                                                
	  p[:password] = params[:password]                                      
	  p[:password_confirmation] = params[:password_confirmation]            
	  update_attributes(p)                                                  
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to determine whether a password has been set             
	# ----------------------------------------------------------------------
	def has_no_password?                                                    
	  self.encrypted_password.blank?                                        
	end                                                                     
	# ----------------------------------------------------------------------
	# new function to provide access to protected method pending_any_confirmation
	# ----------------------------------------------------------------------
	def only_if_unconfirmed                                                 
	  pending_any_confirmation {yield}                                      
	end                                                                     
	# ----------------------------------------------------------------------
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	# **********************************************************************
  	#                                                                 
  	# **********************************************************************
        respond_to :html, :json, :js
        load_and_authorize_resource
  	# **********************************************************************
  	#                                                                
  	# **********************************************************************
  	def index
  	  respond_with do |format|
  	    format.json { render json: UsersDatatable.new(view_context) }   
  	  end
  	end                                                                     
end

app/views/users/_form.html.haml
= form_for(@user, remote: true, :url => registration_path(@user)) do |f|
  %td= f.text_field :name, :placeholder=>"Username"
  %td= f.email_field :email, :placeholder=>"Email"
  %td= f.text_field :accounting_code, :placeholder=>"Accounting Code"
  %td= f.number_field :margin
  %td(style="width:136px;")
  %td   
    = button_tag :type => 'submit', :class => "pull-right btn btn-limekiln-3" do
      %i.font-awesome.icon-plus

      
        
                  

app/views/users/_modal.html.haml
- @users.each do |user|   
  .modal.hide.fade(id = "user_#{ user.id }")  
    .modal-header
      %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
      %h3 
        About to delete Agent
        = user.name
        
    
    .modal-body
      %p 
        .label.label-important Attention!
        Please confirm you want to remove Agent
        = user.name
    
    .modal-footer
      = link_to "Delete", user, :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}
        

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/_user.html.haml
.modal.hide.fade(id = "user_#{ @user.id }")  
  .modal-header
    %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
    %h3 
      About to delete Agent
      = @user.name
      
  
  .modal-body
    %p 
      .label.label-important Attention!
      Please confirm you want to remove Agent
      = @user.name
  
  .modal-footer
    = link_to "Delete", @user, :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}

app/views/users/destroy.js.erb
$('.modal').modal('hide')
$('#tbl_users').dataTable().fnDraw();
$('#row_counter').html($('#tbl_users').dataTable().fnSettings().fnRecordsTotal())





app/views/users/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
/ ------------------------------------------------------------------------------     
.span4
  %h1
    %span.badge.badge-info#row_counter
    #{params[:controller].titleize}
/ ------------------------------------------------------------------------------                                 
.span12                          
  .box   
    .box-content      
      / ------------------------------------------------------------------------
      %table.table(id = "tbl_#{params[:controller]}" style="table-layout: fixed")
        / ----------------------------------------------------------------------
        %thead
          %tr
            %th Name
            %th Email
            / %th Role
            %th Activated At
            %th Sign-in Count 
            %th Last Sign-in 
        / ----------------------------------------------------------------------
        %tbody
            
              
            
              
            