config/routes.rb
SktBilling::Application.routes.draw do


  resources :companies


  resources :clients


  resources :bill_codes


  resources :bills


  resources :payments


  resources :directions


  resources :currencies


  resources :addresses


  resources :accounts


  resources :bill_items


  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :companies, :only => [:index, :update]
  resources :clients, :only => [:index, :update]
  resources :bills, :only => [:index, :show]
  resources :accounts, :only => [:index]
  resources :payments, :only => [:index]
  resources :directions, :only => [:index]
  resources :currencies, :only => [:index]
  resources :addresses, :only => [:index]


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  authenticated :user do
    root :to => 'bills#index'
  end
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    #get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#edit"    
    #match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/bill.rb
class Bill < ActiveRecord::Base       
	# ----------------------------------------------------------------------
  	attr_accessible :company_id, :bill_amount, :bill_code_id, :bill_status, :bill_sent_at
  	# ----------------------------------------------------------------------
  	validates :company_id, :presence => true
  	validates :bill_status, :inclusion => { :in => ['draft', 'sent'] }
  	# ----------------------------------------------------------------------
  	belongs_to :company
  	belongs_to :bill_code
  	has_many :bill_items 
  	accepts_nested_attributes_for :bill_items, :allow_destroy => true 
  	# ----------------------------------------------------------------------
  	default_values :bill_notes => { :value => '', :allows_nil => false },
  			:bill_status => { :value => 'draft', :allows_nil => false },
  			:bill_due_date => { :value => lambda { Time.zone.now.strftime("%d-%m-%Y %H:%M") }, :allows_nil => false },
  			:bill_code_id => { :value => lambda { BillCode.active.first.id }, :allows_nil => false },
  			:bill_vat => { :value => 21.0, :allows_nil => false },
  			:bill_number => { :value => lambda { Bill.first_bill? ? BillCode.active.first.bill_code_start_from : ( Bill.last.bill_number + 1 ) }, :allows_nil => false }  			
  	# ----------------------------------------------------------------------
  	before_destroy { |record| BillItem.destroy_all "bill_id = #{record.id}" }
        # ----------------------------------------------------------------------
        def gross
        	gross = 0
        	self.bill_items.each do |item|
        		gross += item.bill_item_unit_gross
        	end
        	return gross
        end
        # ----------------------------------------------------------------------
        def fees
        	fees = 0
        	self.bill_items.each do |item|
        		fees += item.bill_item_unit_fee
        	end
        	return fees        	
        end  	
        # ----------------------------------------------------------------------
        def currency
        	self.company.company_country[0..1].downcase
        end
        # ----------------------------------------------------------------------
        def code
           return self.company.company_country.to_s + "-" + self.bill_code.bill_code.to_s + "-" + (sprintf '%05d', self.bill_number)	
        end
        # ----------------------------------------------------------------------
  	def self.first_bill?
  		    Bill.all.count > 0 ? false : true
  	end
        # ----------------------------------------------------------------------
        def self.produce(bill_items)
        	@bill = Bill.create(:company_id => bill_items.first.company_id, :bill_code_id => BillCode.active.first.id)
  	  	amount = 0               
  	  	bill_items.each do |bill_item|
  	  	  amount += bill_item.bill_item_unit_cost         
  	      	  bill_item.attributes = { :bill_id => @bill.id }  
  	          bill_item.save!  	          	  	  
  	  	end
  	  	@bill.attributes = { :bill_amount => amount } 
  	  	@bill.save
  	  	return @bill
        end
        # ----------------------------------------------------------------------
        def self.fees()
        	fees = 0
        	Bill.all.each do |bill|
        	  fees += bill.fees
                end
                return fees        	
        end
        # ----------------------------------------------------------------------
        def self.gross()
        	gross = 0
        	Bill.all.each do |bill|
        	  gross += bill.gross
                end
                return gross
        end
        # ----------------------------------------------------------------------
        def self.total()
        	total = 0
        	Bill.all.each do |bill|
        	  total += bill.bill_amount
                end
                return total
        end  
        # ----------------------------------------------------------------------   
        def self.daily_amount
        	daily_amount = 0
        	@time_window = Time.zone.now.beginning_of_day..Time.zone.now
        	return Bill.group_by_day(:created_at, Time.zone, @time_window).sum(:bill_amount)
        end
        # ----------------------------------------------------------------------
        def self.daily_count
        	daily_count = 0
        	@time_window = Time.zone.now.beginning_of_day..Time.zone.now
        	Bill.group_by_day(:created_at, Time.zone, @time_window).count.each do |key, val|
        		daily_count += val
        	end
        	return daily_count        	
        end

        # ----------------------------------------------------------------------
	def self.sync
	          BillItem.to_bill.group_by(&:company_id).each do |company_id, bill_items|
	             Bill.produce(bill_items)
	          end	
	end
	# ----------------------------------------------------------------------
	def self.unsent
	  Bill.where{ bill_status.eq 'draft' }.all 	
	end
	# ----------------------------------------------------------------------    
	def self.invoice
	          Bill.unsent.each do |bill|
		    UserMailer.invoice(bill).deliver
  	  	    bill.update_attributes(:bill_status => 'sent') 
  	  	    bill.update_attributes(:bill_sent_at => Time.zone.now)
	          end	
	end
	# ----------------------------------------------------------------------   
	def self.report
	      UserMailer.activity_report.deliver	
	end
	# ----------------------------------------------------------------------   
	def invoice
	    UserMailer.invoice(self).deliver
	end	
	# ----------------------------------------------------------------------    	
end

app/controllers/bills_controller.rb
class BillsController < InheritedResources::Base
	# ---------------------------------------------------------------------- 
  	before_filter :authenticate_user! 
  	load_and_authorize_resource
	# ---------------------------------------------------------------------- 	
	layout "pdf", :only => [:show]  
	respond_to :html, :json, :js     
	# ---------------------------------------------------------------------- 
  	def index
  	  respond_with do |format|
  	    format.json { render json: BillsDatatable.new(view_context) }  	                                       
  	  end                                                                                         
  	end 		
        # ---------------------------------------------------------------------- 
  	def show
  	  @bill = Bill.find(params[:id])   	 
  	  respond_with(@bill) do |format|
  	    format.pdf {}  	                                       
  	  end                                                                                         
  	end         
  	# ----------------------------------------------------------------------   
end

app/views/bills/_bill.html.haml
%tr(style="cursor:pointer;")
  %td
    = link_to bill_path(bill, :format => 'pdf') do
      = bill.company.company_country.to_s + "-" + bill.bill_code.bill_code.to_s + "-" + bill.bill_number.to_s
  %td
    - @bill_amount = 0
    %p
      = @bill_amount.to_s
    %span.badge.badge-inverse
      = "VAT " + bill.bill_vat.to_i.to_s + "%"
  %td
    %p
      = bill.company.company_email
  %td
    - if bill.bill_sent_at?
      = distance_of_time_in_words(Time.now, bill.created_at).capitalize + " ago"

app/views/bills/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
/ ------------------------------------------------------------------------------
.span4
  %h1
    %span.badge.badge-info#row_counter
    #{params[:controller].titleize}
    
/ --------------------------------------------------------------------------
.span12                          
  .box   
    .box-content      
      / --------------------------------------------------------------------    
      %table.table(id = "tbl_#{params[:controller]}" style="table-layout: fixed")
        / ------------------------------------------------------------------
        %thead
          %tr 
            %th Bill
            %th Amount 
            %th Currency
            %th Recipients
            %th Created
        / ------------------------------------------------------------------    
        %tbody                    

      /- @bills.each do |bill|
      /  = debug bill   
        
        

app/views/bills/show.html.haml
.container.span9
  // -------------------------------------------------------------------------  
  .span4	
    // -------------------------------------------------------------------------  
    .logo
    // -------------------------------------------------------------------------   
    %h4 SKT Srl
    %p
      Sede Legale: Milano,
      %br
      Piazza Duomo 16, 20122
      %br
      CF/P.IVA 07830200965
  // ---------------------------------------------------------------------------
  .span4
    %table.bill-detail-table.pull-right
      %thead
        %tr
          %th= "FATTURA N. " + @bill.code  
      %tbody
        // ---------------------------------------------------------------------
        %tr 
          %td= "DATA: " + Time.now.strftime("%d/%m/%Y") 
  // ---------------------------------------------------------------------------
  .span4  
    %table.bill-detail-table.pull-right  
      %thead
        %tr
          %th CLIENTE
      %tbody
        // ---------------------------------------------------------------------
        %tr 
          %td= @bill.company.company_name
        // ---------------------------------------------------------------------  
        %tr 
          %td= @bill.company.company_address + " - " + @bill.company.company_country
        // ---------------------------------------------------------------------  
        %tr 
          %td= 'P.IVA ' + @bill.company.company_vat.to_s            
        // ---------------------------------------------------------------------  
        %tr 
          %td= 'Tel: ' + @bill.company.company_phone    
        %tr
          %td= 'Email: ' + @bill.company.company_email
  // ---------------------------------------------------------------------------  
  .span8
    // -------------------------------------------------------------------------
    %table.bill-table
      %thead
        %tr(style="text-align:left;")
          %th QTY
          %th Servizio 
          %th Prezzo
          %th IVA
          %th Totale
      %tbody
        - @bill.bill_items.each do |bill_item|
          // ---------------------------------------------------------------------
          %tr
            %td= bill_item.bill_item_quantity.to_s
            %td= bill_item.bill_item_description  
            %td= number_to_currency(bill_item.bill_item_unit_gross, :separator => ",", :precision => 2, :locale => @bill.currency)
            %td= number_to_currency(( bill_item.bill_item_unit_cost-bill_item.bill_item_unit_gross ), :separator => ",", :precision => 2, :locale => @bill.currency)
            %td= number_to_currency(bill_item.bill_item_unit_cost, :separator => ",", :precision => 2, :locale => @bill.currency)
            
    // -------------------------------------------------------------------------
    %table.bill-summary-table.pull-right
      %tbody       
        // ---------------------------------------------------------------------
        %tr 
          %td TOTALE IMPONIBILE
          %td(style="width:80px;")
          %td= number_to_currency(@bill.gross, :separator => ",", :precision => 2, :locale => @bill.currency)
        // ---------------------------------------------------------------------    
        %tr
          %td= "+IVA " + number_to_percentage(@bill.bill_vat, :separator => ",", :precision => 2).to_s
          %td(style="width:80px;")
          %td= number_to_currency((@bill.bill_amount - @bill.gross), :separator => ",", :precision => 2, :locale => @bill.currency)            
        // ---------------------------------------------------------------------    
        %tr
          %td TOTALE FATTURA
          %td(style="width:80px;")
          %td= number_to_currency(@bill.bill_amount, :separator => ",", :precision => 2, :locale => @bill.currency)
  // ---------------------------------------------------------------------------        

  .span4.pull-left
    %p
      BANCA INTESA
      %br
      C/C 100000003481
      %br
      ABI/CAB 03069 34073
      %br
      IBAN IT 68 U 03069 34073 100000003481
      %br
      BIC/SWIFT BPCVIT2S       
    %p
      PAGAMENTO AVVENUTO
  // ---------------------------------------------------------------------------
  .span8.footer
    %p 
      Per qualsiasi informazione a riguardo della presente siete pregati di scrivere a:
      %br
      supporto@helloskt.com 
      
     