config/routes.rb
SktBilling::Application.routes.draw do


  resources :companies


  resources :clients


  resources :bill_codes


  resources :bills


  resources :payments


  resources :directions


  resources :currencies


  resources :addresses


  resources :accounts


  resources :bill_items


  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :companies, :only => [:index, :update]
  resources :clients, :only => [:index, :update]
  resources :bills, :only => [:index, :show]
  resources :accounts, :only => [:index]
  resources :payments, :only => [:index]
  resources :directions, :only => [:index]
  resources :currencies, :only => [:index]
  resources :addresses, :only => [:index]


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  authenticated :user do
    root :to => 'bills#index'
  end
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    #get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#edit"    
    #match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/bill_item.rb
class BillItem < ActiveRecord::Base
	# ----------------------------------------------------------------------
  	attr_accessible :company_id, :bill_item_vat, :client_id, :bill_id, :bill_item_description, :bill_item_discount, :bill_item_quantity, :bill_item_unit_cost, :bill_item_unit_gross, :bill_item_unit_fee, :bill_item_processed_at, :bill_item_transaction_id, :bill_item_currency
  	# ----------------------------------------------------------------------
  	validates :bill_item_description, :bill_item_transaction_id, :bill_item_currency, :bill_item_unit_cost, :presence => true
  	validates :bill_item_discount, :numericality => { :greater_than_or_equal_to => 0, :less_than_or_equal_to => 100}
  	validates :bill_id, :presence => true, :unless => :nested
  	attr_accessor :nested
  	# ----------------------------------------------------------------------
  	belongs_to :bill
  	belongs_to :company
  	belongs_to :client
  	# ----------------------------------------------------------------------
  	default_values :bill_id => { :value => -1, :allows_nil => false },
  			:bill_item_discount => { :value => 0, :allows_nil => false },
  			:bill_item_quantity => { :value => 1, :allows_nil => false },
  			:bill_item_processed_at => { :value => lambda { Time.zone.now.strftime("%d-%m-%Y %H:%M") }, :allows_nil => false },
  			:bill_item_description => { :value => "Ricarica Servizio TELEFREE (Paypal)", :allows_nil => false } 
  	# ----------------------------------------------------------------------
	def self.to_bill
		 BillItem.where{bill_id.eq -1}
	end
	# ----------------------------------------------------------------------   	
	def self.sync	
		  Payment.valid.to_bill.each do |payment|		  	
                        client = Client.find_or_create_by_client_email(:client_country => payment.residence_country, :client_email => payment.payer_email , :client_name => (payment.first_name.to_s + ' ' + payment.last_name.to_s).titleize )                                                
                        company = Company.find_or_create_by_company_email('unknown@skt.com') if !( company = Company.find_by_company_email(payment.account.address.email))		  			 
		  	BillItem.create(:bill_item_vat => payment.tax, :bill_item_unit_cost => payment.amount, :bill_item_unit_fee => payment.fee, :bill_item_unit_gross => payment.gross, :bill_item_currency => payment.currency.to_s, :bill_item_transaction_id => payment.transaction_id.to_s, :bill_item_processed_at => payment.shipped_at, :client_id => client.id, :company_id => company.id)
		  end 
	end
	# ----------------------------------------------------------------------
end

app/controllers/bill_items_controller.rb
class BillItemsController < InheritedResources::Base
	# ---------------------------------------------------------------------- 
  	before_filter :authenticate_user! 
  	load_and_authorize_resource
	# ---------------------------------------------------------------------- 	
	respond_to :html, :json
        # ---------------------------------------------------------------------- 	
  	def index
  	  respond_with do |format|
  	    format.json { render json: BillItemsDatatable.new(view_context) }  
  	  end                                                                                         
  	end 
	# ---------------------------------------------------------------------- 
end

app/views/bill_items/_form.html.haml
= simple_form_for(@bill_item) do |f|
  = f.error_notification

  .form-inputs
    = f.input :bill_item_description
    = f.input :bill_item_unit_cost
    = f.input :bill_item_unit_fee
    = f.input :bill_item_unit_gross
    = f.input :bill_item_quantity
    = f.input :bill_item_discount
    = f.input :bill_id
    = f.input :bill_item_processed_at
    = f.input :bill_item_transaction_id
    = f.input :bill_item_currency
    = f.input :client_id
    = f.input :company_id

  .form-actions
    = f.button :submit

app/views/bill_items/edit.html.haml
%h1 Editing bill_item

= render 'form'

= link_to 'Show', @bill_item
\|
= link_to 'Back', bill_items_path

app/views/bill_items/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
/ ------------------------------------------------------------------------------
.span4
  %h1
    %span.badge.badge-info#row_counter
    #{params[:controller].titleize}            
/ --------------------------------------------------------------------------
.span12                          
  .box 
    .box-content      
      / --------------------------------------------------------------------    
      %table.table(id = "tbl_#{params[:controller]}" style="table-layout: fixed")
        / ------------------------------------------------------------------
        %thead
          %tr
            %th Amount
            %th Gross
            %th Fee   
            %th VAT
            %th Currency
            %th Description
            %th Created
            %th Client
            %th Company
            / %th Transaction            
        / ------------------------------------------------------------------    
        %tbody  
        

app/views/bill_items/new.html.haml
%h1 New bill_item

= render 'form'

= link_to 'Back', bill_items_path

app/views/bill_items/show.html.haml
%p#notice= notice

%p
  %b Bill item description:
  = @bill_item.bill_item_description
%p
  %b Bill item unit cost:
  = @bill_item.bill_item_unit_cost
%p
  %b Bill item unit fee:
  = @bill_item.bill_item_unit_fee
%p
  %b Bill item unit gross:
  = @bill_item.bill_item_unit_gross
%p
  %b Bill item quantity:
  = @bill_item.bill_item_quantity
%p
  %b Bill item discount:
  = @bill_item.bill_item_discount
%p
  %b Bill:
  = @bill_item.bill_id
%p
  %b Bill item processed at:
  = @bill_item.bill_item_processed_at
%p
  %b Bill item transaction:
  = @bill_item.bill_item_transaction_id
%p
  %b Bill item currency:
  = @bill_item.bill_item_currency
%p
  %b Client:
  = @bill_item.client_id
%p
  %b Company:
  = @bill_item.company_id

= link_to 'Edit', edit_bill_item_path(@bill_item)
\|
= link_to 'Back', bill_items_path