config/routes.rb
SktBilling::Application.routes.draw do


  resources :companies


  resources :clients


  resources :bill_codes


  resources :bills


  resources :payments


  resources :directions


  resources :currencies


  resources :addresses


  resources :accounts


  resources :bill_items


  resources :bill_codes
  resources :bill_items, :only => [:index]
  resources :companies, :only => [:index, :update]
  resources :clients, :only => [:index, :update]
  resources :bills, :only => [:index, :show]
  resources :accounts, :only => [:index]
  resources :payments, :only => [:index]
  resources :directions, :only => [:index]
  resources :currencies, :only => [:index]
  resources :addresses, :only => [:index]


  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  devise_for :users, :controllers => { :registrations => "registrations", :confirmations => "confirmations" }
  authenticated :user do
    root :to => 'bills#index'
  end
  as :user do 
    root :to => "devise/sessions#new"    
    get "/login" => "devise/sessions#new"                                 
    post "/login" => "devise/sessions#create"
    delete "/logout" => "devise/sessions#destroy"
    #get "/subscribe" => "devise/registrations#new"
    get "/reset" => "devise/passwords#new"
    put "/reset" => "devise/passwords#edit"    
    #match '/user/confirmation' => 'confirmations#update', :via => :put, :as => :update_user_confirmation
  end 

  resources :users
  match '*a', :to => 'errors#not_found'
  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'
end

app/models/bill_code.rb
class BillCode < ActiveRecord::Base   
	# ----------------------------------------------------------------------
  	attr_accessible :bill_code, :bill_code_start_from, :bill_code_status
  	# ----------------------------------------------------------------------
  	has_many :bills   	
  	# ----------------------------------------------------------------------
  	validates :bill_code, :presence => true  
  	validates_format_of :bill_code, :with => /\A(\d{2})+(_COR)\Z/i, :message => "A Bill Code must be formatted as YY_COR!"
  	validates_uniqueness_of :bill_code, :message => "Bill Codes must be unique!"
  	validates_length_of :bill_code, :minimum => 6, :maximum => 6, :allow_blank => false, :message => "Invalid length!" 
  	validate :on_billing_cycle, :if => :active?
  	# ----------------------------------------------------------------------
  	scope :active, -> { where(:bill_code_status => 1) }
  	# ----------------------------------------------------------------------
  	default_values :bill_code => { :value => lambda { Time.now.strftime("%y") + '_COR' }, :allows_nil => false },
  			:bill_code_start_from => { :value => lambda { sprintf '%05d', 1 }, :allows_nil => false },
  			:bill_code_status => { :value => 0, :allows_nil => false }
  	
  	# ----------------------------------------------------------------------    
  	before_destroy { |record| Bill.destroy_all "bill_code_id = #{record.id}"   }
  	# ---------------------------------------------------------------------- 
  	def on_billing_cycle
  		if BillCode.active.count > 0
  			errors.add(:bill_code_status, "There can only be 1 Bill Code active at a time!")
  		end  		
  	end                             
        # ----------------------------------------------------------------------
  	private
  	  # --------------------------------------------------------------------
  	  def active?
  	  	self.bill_code_status == 1 ? true : false
  	  end
        # ----------------------------------------------------------------------
end

app/controllers/bill_codes_controller.rb
class BillCodesController < ApplicationController
	# ---------------------------------------------------------------------- 
  	before_filter :authenticate_user! 
  	load_and_authorize_resource
	# ---------------------------------------------------------------------- 
	respond_to :html, :json, :js
	has_scope :active 
        # ---------------------------------------------------------------------- 
  	def index
  	  @bill_code = BillCode.new 
  	  respond_with do |format|
  	    format.json { render json: BillCodesDatatable.new(view_context) }
  	  end                                                                                         
  	end         
 	# ----------------------------------------------------------------------  
  	def create  
  	  @bill_code = BillCode.new(params[:bill_code])  	  
  	  respond_to do |format|
  	    if @bill_code.save
  	      flash[:notice] = "Bill Code was successfully created."
  	      format.js {}
  	      format.json { render json: @bill_code, status: :created, location: @bill_code }
  	    else
  	      #format.html { render action: "new" }
  	      messages = @bill_code.errors.full_messages.map { |msg| flash.now[:error] = msg }.join 
  	      format.json { render json: messages.titleize, status: :unprocessable_entity }
  	    end
  	  end    
  	end  
        # ---------------------------------------------------------------------- 
  	def update    
  	  @bill_code = BillCode.find(params[:id])  
  	  @bill_code.update_attributes(params[:bill_code])     
  	  flash[:notice] = "Bill Code was successfully updated." if @bill_code.save
  	  respond_with @bill_code
  	end   
  	# ---------------------------------------------------------------------- 
  	def destroy             
  	  @bill_code = BillCode.find(params[:id])
  	  respond_to do |format|
  	    if @bill_code.destroy
  	      flash[:notice] = "Bill Code was successfully deleted."
  	      format.js {}
  	      format.json { render json: BillCodesDatatable.new(view_context) }
  	    else
  	      format.html { render action: "index" }
  	      format.json { render json: @bill_code.errors, status: :unprocessable_entity }
  	    end
  	  end    
  	end   	
  	# ---------------------------------------------------------------------- 
end

app/views/bill_codes/_bill_code.html.haml
.modal.hide.fade(id = "bill_code_#{ @bill_code.id }")  
  .modal-header
    %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
    %h3 
      About to delete Bill Code
      = @bill_code.bill_code
      
  
  .modal-body
    %p 
      .label.label-important Attention!
      Deleting this Bill Code will also delete any associated Bills.
      There are currently 
      - begin
        - @bill_count = Bill.find_by_bill_code_id(@bill_code.id).count
      - rescue
        - @bill_count = 0    
      = @bill_count
      = @bill_count > 0 ? "Bills associated with this Bill Code." : "Bills associated with this Bill Code, so it's probably safe." 
  
  .modal-footer
    = button_to "Delete", bill_code_path(bill_code), :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}
  

app/views/bill_codes/_form.html.haml
= form_for(@bill_code, remote: true) do |f|
  %td= f.text_field :bill_code, :placeholder=> "Code"
  %td(style="width:260px;")= f.text_field :bill_code_start_from, :placeholder=> "Starting Number"
  %td
    .toggle-active.toggle-modern.pull-right(data-checkbox='check_box')
    = f.check_box :bill_code_status, :class => 'check_box', :style => 'display:none;'
  %td   
    = button_tag :type => 'submit', :class => "pull-right btn btn-limekiln-3" do
      %i.font-awesome.icon-plus
        
                  

app/views/bill_codes/_modal.html.haml
- BillCode.all.each do |bill_code|   
  .modal.hide.fade(id = "bill_code_#{ bill_code.id }")  
    .modal-header
      %button.close(type="button" data-dismiss="modal" aria-hidden="true") &times;
      %h3 
        About to delete Bill Code
        = bill_code.bill_code
        
    
    .modal-body
      %p 
        .label.label-important Attention!
        Deleting this Bill Code will also delete any associated Bills.
        There are currently 
        - @bill_count = 0
        - begin
          - @bill_count = bill_code.bills.count
        - rescue
        = @bill_count
        = @bill_count > 0 ? "Bills associated with this Bill Code." : "Bills associated with this Bill Code, so it's probably safe." 
    
    .modal-footer
      = button_to "Delete", bill_code_path(bill_code), :method => :delete, :remote => 'true', :class => "pull-right btn btn-hem-5", :data => { "loading-text" => "Deleting..."}
        

app/views/bill_codes/create.js.erb
$("<%= escape_javascript(render @bill_code) %>").insertAfter(".container .span12");
$('#tbl_bill_codes').dataTable().fnDraw();
$('#row_counter').html($('#tbl_bill_codes').dataTable().fnSettings().fnRecordsTotal())
$('.modal .modal-footer :submit').button()




app/views/bill_codes/destroy.js.erb
$('.modal').modal('hide')
$('#tbl_bill_codes').dataTable().fnDraw();
$('#row_counter').html($('#tbl_bill_codes').dataTable().fnSettings().fnRecordsTotal())





app/views/bill_codes/index.html.haml
- content_for(:javascript) do
  = javascript_include_tag params[:controller]
/ ------------------------------------------------------------------------------
.span4 
  / ----------------------------------------------------------------------------
  %h1
    %span.badge.badge-info#row_counter
    #{params[:controller].titleize}             
/ ------------------------------------------------------------------------------
.span12                          
  .box   
    .box-content    
      / ------------------------------------------------------------------------
      %table.table(id="tbl_#{params[:controller]}" style="table-layout: fixed")
        / ----------------------------------------------------------------------
        %thead
          %tr 
            %th Code
            %th Start Numbering From  
            /%th 
            %th
            %th     
        / ----------------------------------------------------------------------    
        %tbody
      / ------------------------------------------------------------------------      
      %table.table#tbl_form
        %tbody  
          %tr= render 'form' 
/ ------------------------------------------------------------------------------       
= render 'modal'          